name: Ruff

on: [ push, pull_request ]

jobs:
  ruff:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1